ALTER TABLE risks

MODIFY COLUMN fraud_schema VARCHAR(1000) NOT NULL,
MODIFY COLUMN fraud_motive VARCHAR(1000) NOT NULL,
MODIFY COLUMN fraud_technique VARCHAR(1000) NOT NULL,
MODIFY COLUMN risk_source VARCHAR(1000) NOT NULL,
MODIFY COLUMN root_cause VARCHAR(1000) NOT NULL,
MODIFY COLUMN bispro_control_procedure VARCHAR(1000) NOT NULL,
MODIFY COLUMN qualitative_impact VARCHAR(1000) NOT NULL,
MODIFY COLUMN likehood_justification VARCHAR(1000) NOT NULL,
MODIFY COLUMN impact_justification VARCHAR(1000) NOT NULL,
MODIFY COLUMN strategy_agreement VARCHAR(1000) NOT NULL,
MODIFY COLUMN strategy_recomendation VARCHAR(1000) NOT NULL